version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform:
- x64
- Win32
before_build:
- cmd: premake5.exe vs2017
build:
  project: OpenParrot.sln
  verbosity: minimal
artifacts:
- path: build\bin\release\
  name: OpenParrot$(platform)
deploy:
- provider: GitHub
  auth_token:
    secure: a2B+6mDTHuBa0fw8nm739eGJIZBcZp0IenhKvvXvreLR6ZUoHg9pflMP8ahNUK6o
  repository: teknogods/OpenParrot
  artifact: OpenParrotWin32.zip;OpenParrotx64.zip